services:
  db:
    image: postgres:15.3
    container_name: chat_app_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: chat_app
    ports:
      - "5432:5432"
    volumes:
      - ./chat_db_data:/var/lib/postgresql/data
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
